// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	internal "github.com/secretli/server/internal"
	mock "github.com/stretchr/testify/mock"
)

// SecretRepository is an autogenerated mock type for the SecretRepository type
type SecretRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, publicID
func (_m *SecretRepository) Delete(ctx context.Context, publicID string) error {
	ret := _m.Called(ctx, publicID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, publicID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, publicID
func (_m *SecretRepository) Get(ctx context.Context, publicID string) (internal.Secret, error) {
	ret := _m.Called(ctx, publicID)

	var r0 internal.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (internal.Secret, error)); ok {
		return rf(ctx, publicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) internal.Secret); ok {
		r0 = rf(ctx, publicID)
	} else {
		r0 = ret.Get(0).(internal.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: ctx, publicID
func (_m *SecretRepository) MarkAsRead(ctx context.Context, publicID string) error {
	ret := _m.Called(ctx, publicID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, publicID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: ctx, secret
func (_m *SecretRepository) Store(ctx context.Context, secret internal.Secret) error {
	ret := _m.Called(ctx, secret)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, internal.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretRepository creates a new instance of SecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretRepository {
	mock := &SecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
