forwardedPrefix: "/s/api/"
environment: "release"

resources:
  requests:
    cpu: 5m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi

database:
  host: patrickscheid.de
  dbname: secretli
  user: pgmain
