# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^chart/
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: sqlc
        name: sqlc generation
        entry: bash -c 'sqlc -f db/sqlc.yaml -x generate'
        language: system
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-cyclo
        args: [ -over=15 ]
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
