apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: patrickscheid.de-cert
  namespace: secretli
spec:
  secretName: patrickscheid.de-cert-secret
  dnsNames:
    - patrickscheid.de
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
