apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secretli-route
  namespace: secretli
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`patrickscheid.de`) && (Path(`{{ trimSuffix "/" .Values.forwardedPrefix }}`) || PathPrefix(`{{ trimSuffix "/" .Values.forwardedPrefix }}/`))
      kind: Rule
      services:
        - name: secretli
          port: 8080
  tls:
    secretName: patrickscheid.de-cert-secret
