// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_transfers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const answerTransfer = `-- name: AnswerTransfer :execrows
UPDATE code_transfers
SET answer_share        = $1,
    answer_confirmation = $2
WHERE transfer_id = $3
  AND answer_share IS NULL
  AND receiver_token_hash IS NOT NULL
  AND closed_at IS NULL
  AND expires_at > $4
`

type AnswerTransferParams struct {
	AnswerShare        []byte
	AnswerConfirmation []byte
	TransferID         string
	NowAt              pgtype.Timestamptz
}

// Writes the receiver's answer once, while the transfer is active.
func (q *Queries) AnswerTransfer(ctx context.Context, arg AnswerTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerTransfer,
		arg.AnswerShare,
		arg.AnswerConfirmation,
		arg.TransferID,
		arg.NowAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimTransfer = `-- name: ClaimTransfer :one
UPDATE code_transfers
SET receiver_token_hash = $1
WHERE nameplate = $2
  AND receiver_token_hash IS NULL
  AND closed_at IS NULL
  AND expires_at > $3
RETURNING transfer_id, nameplate, sender_token_hash, receiver_token_hash, offer, answer_share, answer_confirmation, delivery, close_reason, created_at, expires_at, closed_at
`

type ClaimTransferParams struct {
	ReceiverTokenHash pgtype.Text
	Nameplate         int32
	NowAt             pgtype.Timestamptz
}

func (q *Queries) ClaimTransfer(ctx context.Context, arg ClaimTransferParams) (CodeTransfer, error) {
	row := q.db.QueryRow(ctx, claimTransfer, arg.ReceiverTokenHash, arg.Nameplate, arg.NowAt)
	var i CodeTransfer
	err := row.Scan(
		&i.TransferID,
		&i.Nameplate,
		&i.SenderTokenHash,
		&i.ReceiverTokenHash,
		&i.Offer,
		&i.AnswerShare,
		&i.AnswerConfirmation,
		&i.Delivery,
		&i.CloseReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const claimedTransferExists = `-- name: ClaimedTransferExists :one
SELECT EXISTS (
    SELECT 1
    FROM code_transfers
    WHERE nameplate = $1
      AND receiver_token_hash IS NOT NULL
      AND closed_at IS NULL
      AND expires_at > $2
)
`

type ClaimedTransferExistsParams struct {
	Nameplate int32
	NowAt     pgtype.Timestamptz
}

func (q *Queries) ClaimedTransferExists(ctx context.Context, arg ClaimedTransferExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, claimedTransferExists, arg.Nameplate, arg.NowAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const closeExpiredActiveTransfers = `-- name: CloseExpiredActiveTransfers :exec
UPDATE code_transfers
SET close_reason = 'expired',
    closed_at    = $1
WHERE closed_at IS NULL
  AND expires_at <= $1
`

// Frees the nameplates of transfers that ran out before cleanup got to them.
func (q *Queries) CloseExpiredActiveTransfers(ctx context.Context, nowAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, closeExpiredActiveTransfers, nowAt)
	return err
}

const closeTransfer = `-- name: CloseTransfer :execrows
UPDATE code_transfers
SET close_reason = $1,
    closed_at    = $2
WHERE transfer_id = $3
  AND closed_at IS NULL
`

type CloseTransferParams struct {
	CloseReason pgtype.Text
	NowAt       pgtype.Timestamptz
	TransferID  string
}

func (q *Queries) CloseTransfer(ctx context.Context, arg CloseTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTransfer, arg.CloseReason, arg.NowAt, arg.TransferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTransfer = `-- name: CreateTransfer :exec
INSERT INTO code_transfers (
    transfer_id,
    nameplate,
    sender_token_hash,
    offer,
    created_at,
    expires_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateTransferParams struct {
	TransferID      string
	Nameplate       int32
	SenderTokenHash string
	Offer           []byte
	CreatedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.Exec(ctx, createTransfer,
		arg.TransferID,
		arg.Nameplate,
		arg.SenderTokenHash,
		arg.Offer,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteEndedTransfers = `-- name: DeleteEndedTransfers :execrows
DELETE FROM code_transfers
WHERE expires_at < $1
   OR closed_at < $1
`

func (q *Queries) DeleteEndedTransfers(ctx context.Context, endedBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedTransfers, endedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deliverTransfer = `-- name: DeliverTransfer :execrows
UPDATE code_transfers
SET delivery     = $1,
    close_reason = 'done',
    closed_at    = $2
WHERE transfer_id = $3
  AND answer_share IS NOT NULL
  AND closed_at IS NULL
  AND expires_at > $2
`

type DeliverTransferParams struct {
	Delivery   []byte
	NowAt      pgtype.Timestamptz
	TransferID string
}

// Writes the sealed link once, after the answer, and closes the transfer.
func (q *Queries) DeliverTransfer(ctx context.Context, arg DeliverTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, deliverTransfer, arg.Delivery, arg.NowAt, arg.TransferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransfer = `-- name: GetTransfer :one
SELECT transfer_id, nameplate, sender_token_hash, receiver_token_hash, offer, answer_share, answer_confirmation, delivery, close_reason, created_at, expires_at, closed_at
FROM code_transfers
WHERE transfer_id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, transferID string) (CodeTransfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, transferID)
	var i CodeTransfer
	err := row.Scan(
		&i.TransferID,
		&i.Nameplate,
		&i.SenderTokenHash,
		&i.ReceiverTokenHash,
		&i.Offer,
		&i.AnswerShare,
		&i.AnswerConfirmation,
		&i.Delivery,
		&i.CloseReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const lockTransferNameplates = `-- name: LockTransferNameplates :exec
SELECT pg_advisory_xact_lock(7302101)
`

// Serializes nameplate allocation across replicas for one transaction, so
// concurrent creates take consecutive numbers instead of racing for one.
func (q *Queries) LockTransferNameplates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTransferNameplates)
	return err
}

const nextFreeNameplate = `-- name: NextFreeNameplate :one
SELECT n::INTEGER AS nameplate
FROM generate_series(1, $1::INTEGER) AS n
WHERE NOT EXISTS (
    SELECT 1
    FROM code_transfers t
    WHERE t.nameplate = n
      AND t.closed_at IS NULL
)
ORDER BY n
LIMIT 1
`

func (q *Queries) NextFreeNameplate(ctx context.Context, maxNameplate int32) (int32, error) {
	row := q.db.QueryRow(ctx, nextFreeNameplate, maxNameplate)
	var nameplate int32
	err := row.Scan(&nameplate)
	return nameplate, err
}
