// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CodeTransfer struct {
	TransferID         string
	Nameplate          int32
	SenderTokenHash    string
	ReceiverTokenHash  pgtype.Text
	Offer              []byte
	AnswerShare        []byte
	AnswerConfirmation []byte
	Delivery           []byte
	CloseReason        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	ClosedAt           pgtype.Timestamptz
}

type Object struct {
	StorageKey     string
	State          string
	S3UploadID     pgtype.Text
	Doomed         bool
	FailedRemovals int32
}

type RetrievalSession struct {
	SessionTokenHash string
	PublicID         string
	ExpiresAt        pgtype.Timestamptz
}

type Secret struct {
	PublicID          string
	State             string
	StorageKey        string
	MetadataTokenHash pgtype.Text
	BlobTokenHash     pgtype.Text
	DeletionTokenHash pgtype.Text
	EncryptedMeta     pgtype.Text
	BlobSize          int64
	BurnAfterRead     bool
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	Opened            bool
}

type Upload struct {
	SessionID       string
	PublicID        pgtype.Text
	UploadTokenHash string
	State           string
	ExpiresAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	Lifetime        pgtype.Interval
}

type UploadPart struct {
	SessionID  string
	PartNumber int32
	PartOffset int64
	PartSize   int64
	PartSha256 string
	Etag       string
}
