// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CodeTransfer struct {
	TransferID         string
	Nameplate          int32
	SenderTokenHash    string
	ReceiverTokenHash  pgtype.Text
	Offer              []byte
	AnswerShare        []byte
	AnswerConfirmation []byte
	Delivery           []byte
	CloseReason        pgtype.Text
	CreatedAt          pgtype.Timestamptz
	ExpiresAt          pgtype.Timestamptz
	ClosedAt           pgtype.Timestamptz
}

type RetrievalSession struct {
	ID               int64
	PublicID         string
	SessionTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type Secret struct {
	PublicID          string
	MetadataTokenHash string
	BlobTokenHash     string
	DeletionTokenHash string
	EncryptedMeta     string
	BlobSize          int64
	BurnAfterRead     bool
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	RetrievedAt       pgtype.Timestamptz
	StorageKey        string
}

type SecretTombstone struct {
	PublicID          string
	MetadataTokenHash string
	DeletionTokenHash string
	Outcome           string
	BurnAfterRead     bool
	EndedAt           pgtype.Timestamptz
	FirstOpenedAt     pgtype.Timestamptz
	OpenedByOwner     bool
	KeepUntil         pgtype.Timestamptz
}

type UploadPart struct {
	SessionID  string
	PartNumber int32
	PartOffset int64
	PartSize   int64
	PartSha256 string
	Etag       string
	CreatedAt  pgtype.Timestamptz
}

type UploadSession struct {
	SessionID         string
	PublicID          string
	UploadTokenHash   string
	MetadataTokenHash pgtype.Text
	BlobTokenHash     pgtype.Text
	DeletionTokenHash pgtype.Text
	S3UploadID        string
	BlobSize          int64
	EncryptedMeta     pgtype.Text
	BurnAfterRead     bool
	SecretExpiresAt   pgtype.Timestamptz
	UploadExpiresAt   pgtype.Timestamptz
	State             string
	CreatedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	AbortedAt         pgtype.Timestamptz
	StorageKey        string
}
