// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObject = `-- name: CreateObject :exec
INSERT INTO objects (
    storage_key,
    state,
    created_at
)
VALUES (
    $1, 'writing', $2
)
`

type CreateObjectParams struct {
	StorageKey string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) error {
	_, err := q.db.Exec(ctx, createObject, arg.StorageKey, arg.CreatedAt)
	return err
}

const deleteObjects = `-- name: DeleteObjects :execrows
DELETE FROM objects
WHERE storage_key = ANY($1::text[])
`

func (q *Queries) DeleteObjects(ctx context.Context, storageKeys []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteObjects, storageKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const doomObjects = `-- name: DoomObjects :exec
UPDATE objects
SET doomed_at = $1
WHERE storage_key = ANY($2::text[])
  AND doomed_at IS NULL
`

type DoomObjectsParams struct {
	NowAt       pgtype.Timestamptz
	StorageKeys []string
}

func (q *Queries) DoomObjects(ctx context.Context, arg DoomObjectsParams) error {
	_, err := q.db.Exec(ctx, doomObjects, arg.NowAt, arg.StorageKeys)
	return err
}

const listDoomedObjectsForUpdate = `-- name: ListDoomedObjectsForUpdate :many
SELECT o.storage_key, o.state, o.s3_upload_id, o.created_at, o.doomed_at
FROM objects AS o
WHERE o.doomed_at IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM secrets AS s
      WHERE s.storage_key = o.storage_key
  )
ORDER BY o.doomed_at
LIMIT $1
FOR UPDATE OF o SKIP LOCKED
`

// Doomed objects, oldest first, one batch at a time. One a secret still
// points at would be a bug; it is left alone rather than deleted from under
// the secret.
func (q *Queries) ListDoomedObjectsForUpdate(ctx context.Context, batchSize int32) ([]Object, error) {
	rows, err := q.db.Query(ctx, listDoomedObjectsForUpdate, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Object{}
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.StorageKey,
			&i.State,
			&i.S3UploadID,
			&i.CreatedAt,
			&i.DoomedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObjectStored = `-- name: MarkObjectStored :exec
UPDATE objects
SET state = 'stored'
WHERE storage_key = $1
`

func (q *Queries) MarkObjectStored(ctx context.Context, storageKey string) error {
	_, err := q.db.Exec(ctx, markObjectStored, storageKey)
	return err
}

const recordS3UploadID = `-- name: RecordS3UploadID :execrows
UPDATE objects
SET s3_upload_id = $1
WHERE storage_key = $2
  AND state = 'writing'
`

type RecordS3UploadIDParams struct {
	S3UploadID pgtype.Text
	StorageKey string
}

func (q *Queries) RecordS3UploadID(ctx context.Context, arg RecordS3UploadIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordS3UploadID, arg.S3UploadID, arg.StorageKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
