// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_ids.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredPublicIDs = `-- name: DeleteExpiredPublicIDs :execrows
DELETE FROM public_ids
WHERE public_id IN (
    SELECT p.public_id
    FROM public_ids AS p
    WHERE p.expires_at <= $1
      AND NOT EXISTS (
          SELECT 1
          FROM secrets AS s
          WHERE s.public_id = p.public_id
      )
    ORDER BY p.expires_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
`

type DeleteExpiredPublicIDsParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

// Frees one batch of ids past their expiry whose secret is gone, oldest
// first. A secret's id stays while its row does: an upload that outlasts
// its provisional expiry keeps it until it completes or is abandoned.
func (q *Queries) DeleteExpiredPublicIDs(ctx context.Context, arg DeleteExpiredPublicIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPublicIDs, arg.NowAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePublicIDs = `-- name: DeletePublicIDs :exec
DELETE FROM public_ids
WHERE public_id = ANY($1::text[])
`

// An abandoned upload's secret never existed: its id is free again.
func (q *Queries) DeletePublicIDs(ctx context.Context, publicIds []string) error {
	_, err := q.db.Exec(ctx, deletePublicIDs, publicIds)
	return err
}

const registerPublicID = `-- name: RegisterPublicID :exec
INSERT INTO public_ids (
    public_id,
    expires_at
)
VALUES (
    $1, $2
)
`

type RegisterPublicIDParams struct {
	PublicID  string
	ExpiresAt pgtype.Timestamptz
}

// Takes a public id until expires_at. A second upload with the same id fails
// on the primary key, whatever became of the secret that took it first.
func (q *Queries) RegisterPublicID(ctx context.Context, arg RegisterPublicIDParams) error {
	_, err := q.db.Exec(ctx, registerPublicID, arg.PublicID, arg.ExpiresAt)
	return err
}

const setPublicIDExpiry = `-- name: SetPublicIDExpiry :exec
UPDATE public_ids
SET expires_at = $1
WHERE public_id = $2
`

type SetPublicIDExpiryParams struct {
	ExpiresAt pgtype.Timestamptz
	PublicID  string
}

// The completed upload gives the secret, and so its id, the final expiry.
func (q *Queries) SetPublicIDExpiry(ctx context.Context, arg SetPublicIDExpiryParams) error {
	_, err := q.db.Exec(ctx, setPublicIDExpiry, arg.ExpiresAt, arg.PublicID)
	return err
}
