// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieval_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetrievalSession = `-- name: CreateRetrievalSession :exec
INSERT INTO retrieval_sessions (
    session_token_hash,
    public_id,
    expires_at
)
VALUES (
    $1, $2, $3
)
`

type CreateRetrievalSessionParams struct {
	SessionTokenHash string
	PublicID         string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateRetrievalSession(ctx context.Context, arg CreateRetrievalSessionParams) error {
	_, err := q.db.Exec(ctx, createRetrievalSession, arg.SessionTokenHash, arg.PublicID, arg.ExpiresAt)
	return err
}

const deleteExpiredRetrievalSessions = `-- name: DeleteExpiredRetrievalSessions :execrows
DELETE FROM retrieval_sessions
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRetrievalSessions(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRetrievalSessions, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDownloadableSecret = `-- name: GetDownloadableSecret :one
SELECT s.public_id, s.state, s.storage_key, s.metadata_token_hash, s.blob_token_hash, s.deletion_token_hash, s.encrypted_meta, s.blob_size, s.burn_after_read, s.expires_at, s.created_at, s.opened
FROM retrieval_sessions AS rs
JOIN secrets AS s ON s.public_id = rs.public_id
WHERE rs.session_token_hash = $1
  AND rs.public_id = $2
  AND rs.expires_at > $3
  AND s.expires_at > $3
`

type GetDownloadableSecretParams struct {
	SessionTokenHash string
	PublicID         string
	NowAt            pgtype.Timestamptz
}

// The secret a valid session may read, live or closing, until it expires.
// Whatever dooms an object deletes its secret in the same transaction, and
// the secret's sessions with it, so deleting a secret ends running downloads.
func (q *Queries) GetDownloadableSecret(ctx context.Context, arg GetDownloadableSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getDownloadableSecret, arg.SessionTokenHash, arg.PublicID, arg.NowAt)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.State,
		&i.StorageKey,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Opened,
	)
	return i, err
}
