// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrieval_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRetrievalSession = `-- name: CreateRetrievalSession :exec
INSERT INTO retrieval_sessions (
    public_id,
    session_token_hash,
    expires_at,
    created_at
)
VALUES (
    $1, $2, $3, $4
)
`

type CreateRetrievalSessionParams struct {
	PublicID         string
	SessionTokenHash string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateRetrievalSession(ctx context.Context, arg CreateRetrievalSessionParams) error {
	_, err := q.db.Exec(ctx, createRetrievalSession,
		arg.PublicID,
		arg.SessionTokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRetrievalSessions = `-- name: DeleteExpiredRetrievalSessions :execrows
DELETE
FROM retrieval_sessions
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredRetrievalSessions(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRetrievalSessions, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSecretByPublicIDForUpdate = `-- name: GetSecretByPublicIDForUpdate :one
SELECT public_id, metadata_token_hash, blob_token_hash, deletion_token_hash, encrypted_meta, blob_size, burn_after_read, expires_at, created_at, retrieved_at, storage_key
FROM secrets
WHERE public_id = $1
  AND expires_at > $2
FOR UPDATE
`

type GetSecretByPublicIDForUpdateParams struct {
	PublicID string
	NowAt    pgtype.Timestamptz
}

func (q *Queries) GetSecretByPublicIDForUpdate(ctx context.Context, arg GetSecretByPublicIDForUpdateParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByPublicIDForUpdate, arg.PublicID, arg.NowAt)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.StorageKey,
	)
	return i, err
}

const getSecretByRetrievalSession = `-- name: GetSecretByRetrievalSession :one
SELECT
    s.public_id,
    s.metadata_token_hash,
    s.blob_token_hash,
    s.deletion_token_hash,
    s.encrypted_meta,
    s.blob_size,
    s.burn_after_read,
    s.expires_at,
    s.created_at,
    s.retrieved_at,
    s.storage_key
FROM retrieval_sessions AS rs
JOIN secrets AS s ON s.public_id = rs.public_id
WHERE s.public_id = $1
  AND rs.session_token_hash = $2
  AND rs.expires_at > $3
  AND s.expires_at > $3
`

type GetSecretByRetrievalSessionParams struct {
	PublicID         string
	SessionTokenHash string
	NowAt            pgtype.Timestamptz
}

func (q *Queries) GetSecretByRetrievalSession(ctx context.Context, arg GetSecretByRetrievalSessionParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByRetrievalSession, arg.PublicID, arg.SessionTokenHash, arg.NowAt)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.StorageKey,
	)
	return i, err
}
