// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_tombstones.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTombstone = `-- name: CreateTombstone :exec
INSERT INTO secret_tombstones (
    public_id,
    metadata_token_hash,
    deletion_token_hash,
    outcome,
    burn_after_read,
    ended_at,
    first_opened_at,
    opened_by_owner,
    keep_until
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (public_id) DO NOTHING
`

type CreateTombstoneParams struct {
	PublicID          string
	MetadataTokenHash string
	DeletionTokenHash string
	Outcome           string
	BurnAfterRead     bool
	EndedAt           pgtype.Timestamptz
	FirstOpenedAt     pgtype.Timestamptz
	OpenedByOwner     bool
	KeepUntil         pgtype.Timestamptz
}

// What became of a secret. The first outcome recorded stays: a one-time
// secret that was opened and then deleted or expired was opened.
func (q *Queries) CreateTombstone(ctx context.Context, arg CreateTombstoneParams) error {
	_, err := q.db.Exec(ctx, createTombstone,
		arg.PublicID,
		arg.MetadataTokenHash,
		arg.DeletionTokenHash,
		arg.Outcome,
		arg.BurnAfterRead,
		arg.EndedAt,
		arg.FirstOpenedAt,
		arg.OpenedByOwner,
		arg.KeepUntil,
	)
	return err
}

const createTombstonesForExpiredSecrets = `-- name: CreateTombstonesForExpiredSecrets :exec
INSERT INTO secret_tombstones (
    public_id,
    metadata_token_hash,
    deletion_token_hash,
    outcome,
    burn_after_read,
    ended_at,
    first_opened_at,
    opened_by_owner,
    keep_until
)
SELECT
    public_id,
    metadata_token_hash,
    deletion_token_hash,
    'expired',
    burn_after_read,
    expires_at,
    CASE WHEN burn_after_read THEN NULL ELSE retrieved_at END,
    false,
    $1::timestamptz
FROM secrets
WHERE public_id = ANY($2::text[])
  AND expires_at < $3
ON CONFLICT (public_id) DO NOTHING
`

type CreateTombstonesForExpiredSecretsParams struct {
	KeepUntil pgtype.Timestamptz
	PublicIds []string
	NowAt     pgtype.Timestamptz
}

// Tombstones for the expired secrets of a cleanup batch. The consumed
// one-time secrets in the batch have had theirs since they were opened.
func (q *Queries) CreateTombstonesForExpiredSecrets(ctx context.Context, arg CreateTombstonesForExpiredSecretsParams) error {
	_, err := q.db.Exec(ctx, createTombstonesForExpiredSecrets, arg.KeepUntil, arg.PublicIds, arg.NowAt)
	return err
}

const deleteExpiredTombstones = `-- name: DeleteExpiredTombstones :execrows
DELETE FROM secret_tombstones
WHERE keep_until <= $1
`

func (q *Queries) DeleteExpiredTombstones(ctx context.Context, nowAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTombstones, nowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTombstone = `-- name: GetTombstone :one
SELECT public_id, metadata_token_hash, deletion_token_hash, outcome, burn_after_read, ended_at, first_opened_at, opened_by_owner, keep_until
FROM secret_tombstones
WHERE public_id = $1
  AND keep_until > $2
`

type GetTombstoneParams struct {
	PublicID string
	NowAt    pgtype.Timestamptz
}

func (q *Queries) GetTombstone(ctx context.Context, arg GetTombstoneParams) (SecretTombstone, error) {
	row := q.db.QueryRow(ctx, getTombstone, arg.PublicID, arg.NowAt)
	var i SecretTombstone
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.DeletionTokenHash,
		&i.Outcome,
		&i.BurnAfterRead,
		&i.EndedAt,
		&i.FirstOpenedAt,
		&i.OpenedByOwner,
		&i.KeepUntil,
	)
	return i, err
}
