// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSecret = `-- name: CloseSecret :exec
UPDATE secrets
SET state = 'closing',
    created_at = NULL,
    metadata_token_hash = NULL,
    encrypted_meta = NULL,
    blob_token_hash = NULL,
    deletion_token_hash = NULL
WHERE public_id = $1
`

// Opening a one-time secret closes it, whoever opens it. Its row keeps only
// what the download that opened it needs, the object, its size and the
// expiry, until that download has ended.
func (q *Queries) CloseSecret(ctx context.Context, publicID string) error {
	_, err := q.db.Exec(ctx, closeSecret, publicID)
	return err
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (
    public_id,
    state,
    storage_key,
    metadata_token_hash,
    blob_token_hash,
    deletion_token_hash,
    encrypted_meta,
    blob_size,
    burn_after_read,
    expires_at
)
VALUES (
    $1, 'uploading', $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateSecretParams struct {
	PublicID          string
	StorageKey        string
	MetadataTokenHash pgtype.Text
	BlobTokenHash     pgtype.Text
	DeletionTokenHash pgtype.Text
	EncryptedMeta     pgtype.Text
	BlobSize          int64
	BurnAfterRead     bool
	ExpiresAt         pgtype.Timestamptz
}

// A secret is filed when its upload starts, so its public id is taken from
// then on. Its expiry is provisional until the upload completes.
func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.Exec(ctx, createSecret,
		arg.PublicID,
		arg.StorageKey,
		arg.MetadataTokenHash,
		arg.BlobTokenHash,
		arg.DeletionTokenHash,
		arg.EncryptedMeta,
		arg.BlobSize,
		arg.BurnAfterRead,
		arg.ExpiresAt,
	)
	return err
}

const deleteSecretsByPublicIDs = `-- name: DeleteSecretsByPublicIDs :execrows
DELETE FROM secrets
WHERE public_id = ANY($1::text[])
`

// Nothing about a deleted secret is kept but its id, which stays reserved
// until the expiry, and its retrieval sessions go with it. The caller dooms
// the objects in the same transaction.
func (q *Queries) DeleteSecretsByPublicIDs(ctx context.Context, publicIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecretsByPublicIDs, publicIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadingSecrets = `-- name: DeleteUploadingSecrets :many
DELETE FROM secrets
WHERE public_id = ANY($1::text[])
  AND state = 'uploading'
RETURNING public_id, storage_key
`

type DeleteUploadingSecretsRow struct {
	PublicID   string
	StorageKey string
}

// An abandoned upload's secret never existed: its row goes. Returns its id,
// to free, and the key of the object to doom.
func (q *Queries) DeleteUploadingSecrets(ctx context.Context, publicIds []string) ([]DeleteUploadingSecretsRow, error) {
	rows, err := q.db.Query(ctx, deleteUploadingSecrets, publicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteUploadingSecretsRow{}
	for rows.Next() {
		var i DeleteUploadingSecretsRow
		if err := rows.Scan(&i.PublicID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadableSecretForUpdate = `-- name: GetReadableSecretForUpdate :one
SELECT public_id, state, storage_key, metadata_token_hash, blob_token_hash, deletion_token_hash, encrypted_meta, blob_size, burn_after_read, expires_at, created_at, opened
FROM secrets
WHERE public_id = $1
  AND state = 'live'
  AND expires_at > $2
FOR UPDATE
`

type GetReadableSecretForUpdateParams struct {
	PublicID string
	NowAt    pgtype.Timestamptz
}

func (q *Queries) GetReadableSecretForUpdate(ctx context.Context, arg GetReadableSecretForUpdateParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getReadableSecretForUpdate, arg.PublicID, arg.NowAt)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.State,
		&i.StorageKey,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Opened,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT public_id, state, storage_key, metadata_token_hash, blob_token_hash, deletion_token_hash, encrypted_meta, blob_size, burn_after_read, expires_at, created_at, opened
FROM secrets
WHERE public_id = $1
`

func (q *Queries) GetSecret(ctx context.Context, publicID string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, publicID)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.State,
		&i.StorageKey,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Opened,
	)
	return i, err
}

const listDrainedSecretsForUpdate = `-- name: ListDrainedSecretsForUpdate :many
SELECT s.public_id, s.storage_key
FROM secrets AS s
WHERE s.state = 'closing'
  AND NOT EXISTS (
      SELECT 1
      FROM retrieval_sessions AS rs
      WHERE rs.public_id = s.public_id
        AND rs.expires_at > $1
  )
ORDER BY s.public_id
LIMIT $2
FOR UPDATE OF s SKIP LOCKED
`

type ListDrainedSecretsForUpdateParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

type ListDrainedSecretsForUpdateRow struct {
	PublicID   string
	StorageKey string
}

// Closing secrets whose last download session has ended.
func (q *Queries) ListDrainedSecretsForUpdate(ctx context.Context, arg ListDrainedSecretsForUpdateParams) ([]ListDrainedSecretsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listDrainedSecretsForUpdate, arg.NowAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrainedSecretsForUpdateRow{}
	for rows.Next() {
		var i ListDrainedSecretsForUpdateRow
		if err := rows.Scan(&i.PublicID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSecretsForUpdate = `-- name: ListExpiredSecretsForUpdate :many
SELECT public_id, storage_key
FROM secrets
WHERE state <> 'uploading'
  AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredSecretsForUpdateParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

type ListExpiredSecretsForUpdateRow struct {
	PublicID   string
	StorageKey string
}

// Live and closing secrets past their expiry, oldest first. An upload under
// way is left to its own expiry.
func (q *Queries) ListExpiredSecretsForUpdate(ctx context.Context, arg ListExpiredSecretsForUpdateParams) ([]ListExpiredSecretsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listExpiredSecretsForUpdate, arg.NowAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredSecretsForUpdateRow{}
	for rows.Next() {
		var i ListExpiredSecretsForUpdateRow
		if err := rows.Scan(&i.PublicID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUploadStarts = `-- name: LockUploadStarts :exec
SELECT pg_advisory_xact_lock(7302102)
`

// Serializes upload starts while storage is capped, so that two cannot both
// squeeze under the cap with room for one.
func (q *Queries) LockUploadStarts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUploadStarts)
	return err
}

const makeSecretLive = `-- name: MakeSecretLive :execrows
UPDATE secrets
SET state = 'live',
    created_at = $1,
    expires_at = $2
WHERE public_id = $3
  AND state = 'uploading'
`

type MakeSecretLiveParams struct {
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	PublicID  string
}

// The completed upload sets both times, to the minute: the secret's lifetime
// counts from here, and nothing kept tells how long the upload took.
func (q *Queries) MakeSecretLive(ctx context.Context, arg MakeSecretLiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, makeSecretLive, arg.CreatedAt, arg.ExpiresAt, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSecretOpened = `-- name: MarkSecretOpened :exec
UPDATE secrets
SET opened = TRUE
WHERE public_id = $1
`

// A recipient, not the owner, opened a reusable secret.
func (q *Queries) MarkSecretOpened(ctx context.Context, publicID string) error {
	_, err := q.db.Exec(ctx, markSecretOpened, publicID)
	return err
}

const storageStats = `-- name: StorageStats :one
SELECT
    (SELECT count(*) FROM secrets AS l WHERE l.state = 'live' AND l.expires_at > $1)::bigint AS live_secrets,
    (SELECT COALESCE(SUM(h.blob_size), 0) FROM secrets AS h)::bigint AS stored_bytes,
    (SELECT count(*) FROM objects AS o WHERE o.doomed)::bigint AS doomed_objects
`

type StorageStatsRow struct {
	LiveSecrets   int64
	StoredBytes   int64
	DoomedObjects int64
}

// Totals for the metrics: no secret is told apart.
func (q *Queries) StorageStats(ctx context.Context, nowAt pgtype.Timestamptz) (StorageStatsRow, error) {
	row := q.db.QueryRow(ctx, storageStats, nowAt)
	var i StorageStatsRow
	err := row.Scan(&i.LiveSecrets, &i.StoredBytes, &i.DoomedObjects)
	return i, err
}

const storedBytes = `-- name: StoredBytes :one
SELECT COALESCE(SUM(blob_size), 0)::bigint AS stored_bytes
FROM secrets
`

// What the secrets take up in storage, uploads under way and downloads that
// drain included. Every secret holds its object; doomed objects are left
// out, since they are gone within a minute.
func (q *Queries) StoredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, storedBytes)
	var stored_bytes int64
	err := row.Scan(&stored_bytes)
	return stored_bytes, err
}
