// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBurnAfterRead = `-- name: ClaimBurnAfterRead :execrows
UPDATE secrets
SET retrieved_at = $1
WHERE public_id = $2
  AND blob_token_hash = $3
  AND burn_after_read = true
  AND retrieved_at IS NULL
  AND expires_at > $1
`

type ClaimBurnAfterReadParams struct {
	NowAt         pgtype.Timestamptz
	PublicID      string
	BlobTokenHash string
}

func (q *Queries) ClaimBurnAfterRead(ctx context.Context, arg ClaimBurnAfterReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimBurnAfterRead, arg.NowAt, arg.PublicID, arg.BlobTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (
    public_id,
    metadata_token_hash,
    blob_token_hash,
    deletion_token_hash,
    encrypted_meta,
    blob_size,
    burn_after_read,
    expires_at,
    created_at,
    storage_key
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateSecretParams struct {
	PublicID          string
	MetadataTokenHash string
	BlobTokenHash     string
	DeletionTokenHash string
	EncryptedMeta     string
	BlobSize          int64
	BurnAfterRead     bool
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	StorageKey        string
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.Exec(ctx, createSecret,
		arg.PublicID,
		arg.MetadataTokenHash,
		arg.BlobTokenHash,
		arg.DeletionTokenHash,
		arg.EncryptedMeta,
		arg.BlobSize,
		arg.BurnAfterRead,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.StorageKey,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :one
DELETE FROM secrets
WHERE public_id = $1
RETURNING public_id, metadata_token_hash, blob_token_hash, deletion_token_hash, encrypted_meta, blob_size, burn_after_read, expires_at, created_at, retrieved_at, storage_key
`

func (q *Queries) DeleteSecret(ctx context.Context, publicID string) (Secret, error) {
	row := q.db.QueryRow(ctx, deleteSecret, publicID)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.StorageKey,
	)
	return i, err
}

const deleteSecretsByPublicIDs = `-- name: DeleteSecretsByPublicIDs :execrows
DELETE FROM secrets
WHERE public_id = ANY($1::text[])
`

func (q *Queries) DeleteSecretsByPublicIDs(ctx context.Context, publicIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecretsByPublicIDs, publicIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSecretByPublicID = `-- name: GetSecretByPublicID :one
SELECT
    public_id,
    metadata_token_hash,
    blob_token_hash,
    deletion_token_hash,
    encrypted_meta,
    blob_size,
    burn_after_read,
    expires_at,
    created_at,
    retrieved_at,
    storage_key
FROM secrets
WHERE public_id = $1
  AND expires_at > $2
`

type GetSecretByPublicIDParams struct {
	PublicID string
	NowAt    pgtype.Timestamptz
}

func (q *Queries) GetSecretByPublicID(ctx context.Context, arg GetSecretByPublicIDParams) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretByPublicID, arg.PublicID, arg.NowAt)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.StorageKey,
	)
	return i, err
}

const getSecretIgnoringExpiry = `-- name: GetSecretIgnoringExpiry :one
SELECT public_id, metadata_token_hash, blob_token_hash, deletion_token_hash, encrypted_meta, blob_size, burn_after_read, expires_at, created_at, retrieved_at, storage_key
FROM secrets
WHERE public_id = $1
`

// The row whatever its state, to tell what became of an expired secret the
// cleanup has not reached yet.
func (q *Queries) GetSecretIgnoringExpiry(ctx context.Context, publicID string) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecretIgnoringExpiry, publicID)
	var i Secret
	err := row.Scan(
		&i.PublicID,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.EncryptedMeta,
		&i.BlobSize,
		&i.BurnAfterRead,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RetrievedAt,
		&i.StorageKey,
	)
	return i, err
}

const markSecretOpened = `-- name: MarkSecretOpened :exec
UPDATE secrets
SET retrieved_at = $1
WHERE public_id = $2
  AND retrieved_at IS NULL
`

type MarkSecretOpenedParams struct {
	NowAt    pgtype.Timestamptz
	PublicID string
}

// The first time a recipient opens a reusable secret.
func (q *Queries) MarkSecretOpened(ctx context.Context, arg MarkSecretOpenedParams) error {
	_, err := q.db.Exec(ctx, markSecretOpened, arg.NowAt, arg.PublicID)
	return err
}

const selectSecretsForCleanup = `-- name: SelectSecretsForCleanup :many
SELECT s.public_id, s.storage_key
FROM secrets AS s
WHERE s.expires_at < $1
   OR (
       s.burn_after_read = true
       AND s.retrieved_at IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM retrieval_sessions AS rs
           WHERE rs.public_id = s.public_id
             AND rs.expires_at > $1
       )
   )
ORDER BY s.expires_at
LIMIT $2
FOR UPDATE OF s SKIP LOCKED
`

type SelectSecretsForCleanupParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

type SelectSecretsForCleanupRow struct {
	PublicID   string
	StorageKey string
}

// Expired secrets and consumed burn-after-read secrets whose retrieval
// sessions have all ended, oldest first, one batch at a time. Postgres plans
// the OR as a BitmapOr over idx_secrets_expires_at and the partial
// consumed-burn index, so the cost follows the rows due, not the table size.
func (q *Queries) SelectSecretsForCleanup(ctx context.Context, arg SelectSecretsForCleanupParams) ([]SelectSecretsForCleanupRow, error) {
	rows, err := q.db.Query(ctx, selectSecretsForCleanup, arg.NowAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectSecretsForCleanupRow{}
	for rows.Next() {
		var i SelectSecretsForCleanupRow
		if err := rows.Scan(&i.PublicID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
