// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadPart = `-- name: CreateUploadPart :one
INSERT INTO upload_parts (
    session_id,
    part_number,
    part_offset,
    part_size,
    part_sha256,
    etag,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
`

type CreateUploadPartParams struct {
	SessionID  string
	PartNumber int32
	PartOffset int64
	PartSize   int64
	PartSha256 string
	Etag       string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateUploadPart(ctx context.Context, arg CreateUploadPartParams) (UploadPart, error) {
	row := q.db.QueryRow(ctx, createUploadPart,
		arg.SessionID,
		arg.PartNumber,
		arg.PartOffset,
		arg.PartSize,
		arg.PartSha256,
		arg.Etag,
		arg.CreatedAt,
	)
	var i UploadPart
	err := row.Scan(
		&i.SessionID,
		&i.PartNumber,
		&i.PartOffset,
		&i.PartSize,
		&i.PartSha256,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const createUploadSession = `-- name: CreateUploadSession :exec
INSERT INTO upload_sessions (
    session_id,
    public_id,
    upload_token_hash,
    metadata_token_hash,
    blob_token_hash,
    deletion_token_hash,
    s3_upload_id,
    blob_size,
    encrypted_meta,
    burn_after_read,
    secret_expires_at,
    upload_expires_at,
    created_at,
    storage_key,
    state
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 'pending'
)
`

type CreateUploadSessionParams struct {
	SessionID         string
	PublicID          string
	UploadTokenHash   string
	MetadataTokenHash pgtype.Text
	BlobTokenHash     pgtype.Text
	DeletionTokenHash pgtype.Text
	S3UploadID        string
	BlobSize          int64
	EncryptedMeta     pgtype.Text
	BurnAfterRead     bool
	SecretExpiresAt   pgtype.Timestamptz
	UploadExpiresAt   pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	StorageKey        string
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error {
	_, err := q.db.Exec(ctx, createUploadSession,
		arg.SessionID,
		arg.PublicID,
		arg.UploadTokenHash,
		arg.MetadataTokenHash,
		arg.BlobTokenHash,
		arg.DeletionTokenHash,
		arg.S3UploadID,
		arg.BlobSize,
		arg.EncryptedMeta,
		arg.BurnAfterRead,
		arg.SecretExpiresAt,
		arg.UploadExpiresAt,
		arg.CreatedAt,
		arg.StorageKey,
	)
	return err
}

const deleteFinishedUploadSessions = `-- name: DeleteFinishedUploadSessions :execrows
DELETE FROM upload_sessions
WHERE state <> 'pending'
  AND COALESCE(completed_at, aborted_at) < $1
`

func (q *Queries) DeleteFinishedUploadSessions(ctx context.Context, finishedBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedUploadSessions, finishedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadPartsBySession = `-- name: DeleteUploadPartsBySession :exec
DELETE FROM upload_parts
WHERE session_id = $1
`

func (q *Queries) DeleteUploadPartsBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteUploadPartsBySession, sessionID)
	return err
}

const getUploadPartForUpdate = `-- name: GetUploadPartForUpdate :one
SELECT session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
FROM upload_parts
WHERE session_id = $1
  AND part_number = $2
FOR UPDATE
`

type GetUploadPartForUpdateParams struct {
	SessionID  string
	PartNumber int32
}

func (q *Queries) GetUploadPartForUpdate(ctx context.Context, arg GetUploadPartForUpdateParams) (UploadPart, error) {
	row := q.db.QueryRow(ctx, getUploadPartForUpdate, arg.SessionID, arg.PartNumber)
	var i UploadPart
	err := row.Scan(
		&i.SessionID,
		&i.PartNumber,
		&i.PartOffset,
		&i.PartSize,
		&i.PartSha256,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT session_id, public_id, upload_token_hash, metadata_token_hash, blob_token_hash, deletion_token_hash, s3_upload_id, blob_size, encrypted_meta, burn_after_read, secret_expires_at, upload_expires_at, state, created_at, completed_at, aborted_at, storage_key
FROM upload_sessions
WHERE session_id = $1
`

func (q *Queries) GetUploadSession(ctx context.Context, sessionID string) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSession, sessionID)
	var i UploadSession
	err := row.Scan(
		&i.SessionID,
		&i.PublicID,
		&i.UploadTokenHash,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.S3UploadID,
		&i.BlobSize,
		&i.EncryptedMeta,
		&i.BurnAfterRead,
		&i.SecretExpiresAt,
		&i.UploadExpiresAt,
		&i.State,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.AbortedAt,
		&i.StorageKey,
	)
	return i, err
}

const getUploadSessionForUpdate = `-- name: GetUploadSessionForUpdate :one
SELECT session_id, public_id, upload_token_hash, metadata_token_hash, blob_token_hash, deletion_token_hash, s3_upload_id, blob_size, encrypted_meta, burn_after_read, secret_expires_at, upload_expires_at, state, created_at, completed_at, aborted_at, storage_key
FROM upload_sessions
WHERE session_id = $1
FOR UPDATE
`

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, sessionID string) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, sessionID)
	var i UploadSession
	err := row.Scan(
		&i.SessionID,
		&i.PublicID,
		&i.UploadTokenHash,
		&i.MetadataTokenHash,
		&i.BlobTokenHash,
		&i.DeletionTokenHash,
		&i.S3UploadID,
		&i.BlobSize,
		&i.EncryptedMeta,
		&i.BurnAfterRead,
		&i.SecretExpiresAt,
		&i.UploadExpiresAt,
		&i.State,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.AbortedAt,
		&i.StorageKey,
	)
	return i, err
}

const listExpiredUploadSessionsForUpdate = `-- name: ListExpiredUploadSessionsForUpdate :many
SELECT session_id, public_id, upload_token_hash, metadata_token_hash, blob_token_hash, deletion_token_hash, s3_upload_id, blob_size, encrypted_meta, burn_after_read, secret_expires_at, upload_expires_at, state, created_at, completed_at, aborted_at, storage_key
FROM upload_sessions
WHERE state = 'pending'
  AND upload_expires_at < $1
ORDER BY upload_expires_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredUploadSessionsForUpdateParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) ListExpiredUploadSessionsForUpdate(ctx context.Context, arg ListExpiredUploadSessionsForUpdateParams) ([]UploadSession, error) {
	rows, err := q.db.Query(ctx, listExpiredUploadSessionsForUpdate, arg.NowAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.SessionID,
			&i.PublicID,
			&i.UploadTokenHash,
			&i.MetadataTokenHash,
			&i.BlobTokenHash,
			&i.DeletionTokenHash,
			&i.S3UploadID,
			&i.BlobSize,
			&i.EncryptedMeta,
			&i.BurnAfterRead,
			&i.SecretExpiresAt,
			&i.UploadExpiresAt,
			&i.State,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.AbortedAt,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadPartsBySession = `-- name: ListUploadPartsBySession :many
SELECT session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
FROM upload_parts
WHERE session_id = $1
ORDER BY part_number
`

func (q *Queries) ListUploadPartsBySession(ctx context.Context, sessionID string) ([]UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadPartsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.SessionID,
			&i.PartNumber,
			&i.PartOffset,
			&i.PartSize,
			&i.PartSha256,
			&i.Etag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadSessionAborted = `-- name: MarkUploadSessionAborted :execrows
UPDATE upload_sessions
SET state = 'aborted',
    aborted_at = $1,
    metadata_token_hash = NULL,
    blob_token_hash = NULL,
    deletion_token_hash = NULL,
    encrypted_meta = NULL
WHERE session_id = $2
  AND state = 'pending'
`

type MarkUploadSessionAbortedParams struct {
	NowAt     pgtype.Timestamptz
	SessionID string
}

func (q *Queries) MarkUploadSessionAborted(ctx context.Context, arg MarkUploadSessionAbortedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadSessionAborted, arg.NowAt, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUploadSessionCompleted = `-- name: MarkUploadSessionCompleted :exec
UPDATE upload_sessions
SET state = 'completed',
    completed_at = $1,
    metadata_token_hash = NULL,
    blob_token_hash = NULL,
    deletion_token_hash = NULL,
    encrypted_meta = NULL
WHERE session_id = $2
`

type MarkUploadSessionCompletedParams struct {
	NowAt     pgtype.Timestamptz
	SessionID string
}

// The share material now lives on the secret row; the session keeps only
// what a repeated complete needs.
func (q *Queries) MarkUploadSessionCompleted(ctx context.Context, arg MarkUploadSessionCompletedParams) error {
	_, err := q.db.Exec(ctx, markUploadSessionCompleted, arg.NowAt, arg.SessionID)
	return err
}

const markUploadSessionsAborted = `-- name: MarkUploadSessionsAborted :execrows
UPDATE upload_sessions
SET state = 'aborted',
    aborted_at = $1,
    metadata_token_hash = NULL,
    blob_token_hash = NULL,
    deletion_token_hash = NULL,
    encrypted_meta = NULL
WHERE session_id = ANY($2::text[])
  AND state = 'pending'
`

type MarkUploadSessionsAbortedParams struct {
	NowAt      pgtype.Timestamptz
	SessionIds []string
}

func (q *Queries) MarkUploadSessionsAborted(ctx context.Context, arg MarkUploadSessionsAbortedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadSessionsAborted, arg.NowAt, arg.SessionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const secretExistsByPublicID = `-- name: SecretExistsByPublicID :one
SELECT EXISTS (
    SELECT 1
    FROM secrets
    WHERE public_id = $1
)
`

func (q *Queries) SecretExistsByPublicID(ctx context.Context, publicID string) (bool, error) {
	row := q.db.QueryRow(ctx, secretExistsByPublicID, publicID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const uploadSessionExists = `-- name: UploadSessionExists :one
SELECT EXISTS (
    SELECT 1
    FROM upload_sessions
    WHERE session_id = $1
)
`

func (q *Queries) UploadSessionExists(ctx context.Context, sessionID string) (bool, error) {
	row := q.db.QueryRow(ctx, uploadSessionExists, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
