// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUpload = `-- name: CreateUpload :exec
INSERT INTO uploads (
    session_id,
    public_id,
    upload_token_hash,
    state,
    expires_at
)
VALUES (
    $1, $2, $3, 'uploading', $4
)
`

type CreateUploadParams struct {
	SessionID       string
	PublicID        pgtype.Text
	UploadTokenHash string
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) error {
	_, err := q.db.Exec(ctx, createUpload,
		arg.SessionID,
		arg.PublicID,
		arg.UploadTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createUploadPart = `-- name: CreateUploadPart :one
INSERT INTO upload_parts (
    session_id,
    part_number,
    part_offset,
    part_size,
    part_sha256,
    etag,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
`

type CreateUploadPartParams struct {
	SessionID  string
	PartNumber int32
	PartOffset int64
	PartSize   int64
	PartSha256 string
	Etag       string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateUploadPart(ctx context.Context, arg CreateUploadPartParams) (UploadPart, error) {
	row := q.db.QueryRow(ctx, createUploadPart,
		arg.SessionID,
		arg.PartNumber,
		arg.PartOffset,
		arg.PartSize,
		arg.PartSha256,
		arg.Etag,
		arg.CreatedAt,
	)
	var i UploadPart
	err := row.Scan(
		&i.SessionID,
		&i.PartNumber,
		&i.PartOffset,
		&i.PartSize,
		&i.PartSha256,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFinishedUploads = `-- name: DeleteFinishedUploads :execrows
DELETE FROM uploads
WHERE state <> 'uploading'
  AND finished_at < $1
`

// Finished uploads are kept for an hour so a repeated complete or abort
// gets the same answer; their parts go with them.
func (q *Queries) DeleteFinishedUploads(ctx context.Context, finishedBefore pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinishedUploads, finishedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadParts = `-- name: DeleteUploadParts :exec
DELETE FROM upload_parts
WHERE session_id = $1
`

func (q *Queries) DeleteUploadParts(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteUploadParts, sessionID)
	return err
}

const getUpload = `-- name: GetUpload :one
SELECT
    u.session_id,
    u.public_id,
    u.upload_token_hash,
    u.state,
    u.expires_at,
    u.finished_at,
    s.storage_key,
    s.blob_size,
    s.expires_at AS secret_expires_at,
    o.s3_upload_id
FROM uploads AS u
LEFT JOIN secrets AS s ON s.public_id = u.public_id
LEFT JOIN objects AS o ON o.storage_key = s.storage_key
WHERE u.session_id = $1
`

type GetUploadRow struct {
	SessionID       string
	PublicID        pgtype.Text
	UploadTokenHash string
	State           string
	ExpiresAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	StorageKey      pgtype.Text
	BlobSize        pgtype.Int8
	SecretExpiresAt pgtype.Timestamptz
	S3UploadID      pgtype.Text
}

// The upload with what it needs of its secret and object, while the secret
// has them.
func (q *Queries) GetUpload(ctx context.Context, sessionID string) (GetUploadRow, error) {
	row := q.db.QueryRow(ctx, getUpload, sessionID)
	var i GetUploadRow
	err := row.Scan(
		&i.SessionID,
		&i.PublicID,
		&i.UploadTokenHash,
		&i.State,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.StorageKey,
		&i.BlobSize,
		&i.SecretExpiresAt,
		&i.S3UploadID,
	)
	return i, err
}

const getUploadForUpdate = `-- name: GetUploadForUpdate :one
SELECT
    u.session_id,
    u.public_id,
    u.upload_token_hash,
    u.state,
    u.expires_at,
    u.finished_at,
    s.storage_key,
    s.blob_size,
    s.expires_at AS secret_expires_at,
    o.s3_upload_id
FROM uploads AS u
LEFT JOIN secrets AS s ON s.public_id = u.public_id
LEFT JOIN objects AS o ON o.storage_key = s.storage_key
WHERE u.session_id = $1
FOR UPDATE OF u
`

type GetUploadForUpdateRow struct {
	SessionID       string
	PublicID        pgtype.Text
	UploadTokenHash string
	State           string
	ExpiresAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	StorageKey      pgtype.Text
	BlobSize        pgtype.Int8
	SecretExpiresAt pgtype.Timestamptz
	S3UploadID      pgtype.Text
}

func (q *Queries) GetUploadForUpdate(ctx context.Context, sessionID string) (GetUploadForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUploadForUpdate, sessionID)
	var i GetUploadForUpdateRow
	err := row.Scan(
		&i.SessionID,
		&i.PublicID,
		&i.UploadTokenHash,
		&i.State,
		&i.ExpiresAt,
		&i.FinishedAt,
		&i.StorageKey,
		&i.BlobSize,
		&i.SecretExpiresAt,
		&i.S3UploadID,
	)
	return i, err
}

const getUploadPartForUpdate = `-- name: GetUploadPartForUpdate :one
SELECT session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
FROM upload_parts
WHERE session_id = $1
  AND part_number = $2
FOR UPDATE
`

type GetUploadPartForUpdateParams struct {
	SessionID  string
	PartNumber int32
}

func (q *Queries) GetUploadPartForUpdate(ctx context.Context, arg GetUploadPartForUpdateParams) (UploadPart, error) {
	row := q.db.QueryRow(ctx, getUploadPartForUpdate, arg.SessionID, arg.PartNumber)
	var i UploadPart
	err := row.Scan(
		&i.SessionID,
		&i.PartNumber,
		&i.PartOffset,
		&i.PartSize,
		&i.PartSha256,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredUploadsForUpdate = `-- name: ListExpiredUploadsForUpdate :many
SELECT session_id
FROM uploads
WHERE state = 'uploading'
  AND expires_at < $1
ORDER BY expires_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListExpiredUploadsForUpdateParams struct {
	NowAt     pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) ListExpiredUploadsForUpdate(ctx context.Context, arg ListExpiredUploadsForUpdateParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredUploadsForUpdate, arg.NowAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadParts = `-- name: ListUploadParts :many
SELECT session_id, part_number, part_offset, part_size, part_sha256, etag, created_at
FROM upload_parts
WHERE session_id = $1
ORDER BY part_number
`

func (q *Queries) ListUploadParts(ctx context.Context, sessionID string) ([]UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadParts, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.SessionID,
			&i.PartNumber,
			&i.PartOffset,
			&i.PartSize,
			&i.PartSha256,
			&i.Etag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUploadCompleted = `-- name: MarkUploadCompleted :exec
UPDATE uploads
SET state = 'completed',
    finished_at = $1
WHERE session_id = $2
  AND state = 'uploading'
`

type MarkUploadCompletedParams struct {
	NowAt     pgtype.Timestamptz
	SessionID string
}

func (q *Queries) MarkUploadCompleted(ctx context.Context, arg MarkUploadCompletedParams) error {
	_, err := q.db.Exec(ctx, markUploadCompleted, arg.NowAt, arg.SessionID)
	return err
}

const markUploadsAbandoned = `-- name: MarkUploadsAbandoned :many
UPDATE uploads
SET state = 'abandoned',
    finished_at = $1
WHERE session_id = ANY($2::text[])
  AND state = 'uploading'
RETURNING public_id
`

type MarkUploadsAbandonedParams struct {
	NowAt      pgtype.Timestamptz
	SessionIds []string
}

// Returns the public ids of the abandoned uploads' secrets.
func (q *Queries) MarkUploadsAbandoned(ctx context.Context, arg MarkUploadsAbandonedParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, markUploadsAbandoned, arg.NowAt, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var public_id pgtype.Text
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
