// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SecretsColumns holds the columns for the "secrets" table.
	SecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_id", Type: field.TypeString, Unique: true},
		{Name: "retrieval_token", Type: field.TypeString},
		{Name: "deletion_token", Type: field.TypeString},
		{Name: "nonce", Type: field.TypeString},
		{Name: "encrypted_data", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "burn_after_read", Type: field.TypeBool},
		{Name: "already_read", Type: field.TypeBool},
	}
	// SecretsTable holds the schema information for the "secrets" table.
	SecretsTable = &schema.Table{
		Name:       "secrets",
		Columns:    SecretsColumns,
		PrimaryKey: []*schema.Column{SecretsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SecretsTable,
	}
)

func init() {
}
